import type { HologramParams } from "../types";

/**
 * Engine defaults for every hologram parameter. The Presence stage and the
 * debug controls override these (see utils/hologramDefaults.ts).
 */
export const ENGINE_DEFAULTS: HologramParams = {
  particleCount: 50_000,
  autoRotateSpeed: 0.8,
  color: "#8aa0b8",
  floatAmp: 0.01,
  breathAmp: 0,
  sphereSize: 0.01,
  ambient: 0.31,
  wrap: 0.87,
  light1X: 0,
  light1Y: 4,
  light1Z: 0,
  light1Color: "#ffffff",
  light1Intensity: 1.0,
  light2X: 0,
  light2Y: -4,
  light2Z: 0,
  light2Color: "#4488ff",
  light2Intensity: 0.5,
  volumeStrength: 0.79,
  modelX: 0,
  modelY: 1.0,
  modelZ: 0,
  initialModelScale: 0.6,
  noiseAmp: 0.08,
  noiseScale: 0.6,
  noiseSpeed: 0.15,
  noiseGain: 0.5,
  maskScale: 0.4,
  maskSpeed: 0.04,
  maskContrast: 1.5,
  mouseRadius: 1.5,
  mouseStrength: 0.6,
  springStiffness: 5.0,
  springDamping: 3.0,
  pushStrength: 12.0,
  mouseScatter: 0.6,
  mouseGlowColor: "#ffffff",
  mouseGlowPassive: 0.0,
  mouseGlowActive: 1.5,
  mouseGlowPow: 2.0,
  mouseGlowDecay: 1.5,
  mouseLerp: 6.0,
  bloomStrength: 0.4,
  bloomRadius: 0.4,
  bloomThreshold: 0.1,
  chromaticStr: 0.0,
  transitionDeformDur: 0.5,
  transitionMorphDur: 1.2,
  transitionReformDur: 0.7,
  transitionMaskContrast: 0.2,
  transitionGlowScale: 1.0,
  cylVisible: true,
  cylRadius: 1.8,
  cylHeight: 3.5,
  cylColor: "#88ccff",
  cylNoiseScale: 2.0,
  cylLineWidth: 0.08,
  cylFresnelPow: 2.0,
  cylBaseOpacity: 0.15,
  cylLineOpacity: 0.6,
  cylNoiseSpeed: 0.3,
  cylPulseSpeed: 0.8,
  cylPulseAmp: 0.4,
  cylPulseEasing: 2.5,
  cylWaveFreq: 2.0,
  cylTexRepeat: 3,
  cylY: 0,
  gridVisible: true,
  gridColor: "#c8d4de",
  gridBaseOpacity: 0.12,
  gridWaveAmp: 0.55,
  gridNoiseScale: 0.18,
  gridWaveSpeed: 0.07,
  gridDensity: 1.1,
  gridDotSize: 0.07,
  ringVisible: true,
  ringRadius: 1.95,
  ringThickness: 0.03,
  ringGap: 20,
  ringColor: "#ffffff",
  ringOpacity: 0.9,
  ringBrightness: 3.0,
  camIntensity: 12,
  camStiffness: 3.0,
  camDamping: 4.0,
  bgColorCenter: "#d2dde8",
  bgColorMid: "#a0b4c8",
  bgColorEdge: "#7a96aa",
  entranceMorphDur: 0.7,
  entranceReformDur: 0.35,
};

/** Merge props over the defaults, ignoring props that are `undefined`. */
export function resolveParams(props: Partial<HologramParams>): HologramParams {
  const params = { ...ENGINE_DEFAULTS } as Record<string, unknown>;
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined && key in ENGINE_DEFAULTS) params[key] = value;
  }
  return params as HologramParams;
}
