import type { HologramParams } from "../types";

/**
 * Tuned hologram values — the defaults of the Leva debug controls.
 * Production renders with these directly, so the Leva package is only
 * downloaded when the debug controls are switched on (?debug=1).
 */
export const HOLOGRAM_DEFAULTS = {
  particleCount: 60000,
  color: "#99a5b7",
  ambient: 0.2,
  wrap: 0.35,
  volumeStrength: 0.67,
  sphereSize: 0.014,
  modelX: 0,
  modelY: -1.2,
  modelZ: 0,
  mouseRadius: 2.15,
  mouseStrength: 4.9,
  pushStrength: 2.5,
  springStiffness: 40,
  springDamping: 20,
  mouseScatter: 1,
  mouseGlowColor: "#ffada7",
  mouseGlowPassive: 3,
  mouseGlowActive: 6,
  mouseGlowDecay: 0.3,
  mouseGlowPow: 6.0,
  mouseLerp: 1.5,
  bloomStrength: 0.65,
  bloomRadius: 0.65,
  bloomThreshold: 0.34,
  chromaticStr: 0.05,
  light1X: 0,
  light1Y: 5,
  light1Z: 2,
  light1Color: "#ffffff",
  light1Intensity: 1.5,
  light2X: 0,
  light2Y: -5,
  light2Z: -2,
  light2Color: "#f2e0e0",
  light2Intensity: 1.1,
  floatAmp: 0.01,
  autoRotateSpeed: 2.53,
  noiseAmp: 0.72,
  noiseScale: 3.0,
  noiseSpeed: 1,
  noiseGain: 0.65,
  maskScale: 0.95,
  maskSpeed: 0.5,
  maskContrast: 3.8,
  transitionDeformDur: 0.4,
  transitionMorphDur: 2.05,
  transitionReformDur: 0.45,
  transitionMaskContrast: 1.65,
  transitionGlowScale: 1.0,
  entranceMorphDur: 1.8,
  entranceReformDur: 1.1,
  cylVisible: true,
  cylColor: "#ffffff",
  cylRadius: 1.95,
  cylHeight: 5.3,
  cylNoiseScale: 0.2,
  cylLineWidth: 0.22,
  cylFresnelPow: 1.6,
  cylBaseOpacity: 0.0,
  cylLineOpacity: 1,
  cylNoiseSpeed: 0.15,
  cylPulseSpeed: 2.5,
  cylPulseAmp: 0.68,
  cylPulseEasing: 2.5,
  cylWaveFreq: 2.0,
  cylTexRepeat: 8.5,
  cylY: -0.85,
  gridVisible: true,
  gridColor: "#c8d4de",
  gridBaseOpacity: 0.31,
  gridWaveAmp: 0.73,
  gridNoiseScale: 0.44,
  gridWaveSpeed: 0.62,
  gridDensity: 2.15,
  gridDotSize: 0.04,
  ringVisible: true,
  ringColor: "#ffffff",
  ringThickness: 0.03,
  ringBrightness: 3.0,
  ringOpacity: 0.9,
  ringRadius: 1.95,
  ringGap: 20,
  bgColorCenter: "#495155",
  bgColorMid: "#495258",
  bgColorEdge: "#305269",
  camIntensity: 1,
  camStiffness: 3.0,
  camDamping: 4.0,
} satisfies Partial<HologramParams>;

export type HologramControlValues = typeof HOLOGRAM_DEFAULTS;
