"use client";

import { useControls, folder, button } from "leva";
import { HOLOGRAM_DEFAULTS } from "./hologramDefaults";

/**
 * Leva debug controls for the hologram. Only imported by the debug panel,
 * which is loaded on demand — see debug/HologramDebugPanel.tsx.
 * Default values live in ./hologramDefaults.ts.
 */
export function useHologramControls(onReplay: () => void) {
  return useControls("Hologram", {
    Geometry: folder(
      {
        particleCount: {
          value: HOLOGRAM_DEFAULTS.particleCount,
          min: 1000,
          max: 150000,
          step: 1000,
          label: "Particles",
        },
      },
      { collapsed: false },
    ),
    Material: folder(
      {
        color: { value: HOLOGRAM_DEFAULTS.color, label: "Color" },
        ambient: { value: HOLOGRAM_DEFAULTS.ambient, min: 0, max: 1, step: 0.01, label: "Ambient" },
        wrap: { value: HOLOGRAM_DEFAULTS.wrap, min: 0, max: 1, step: 0.01, label: "Wrap" },
        volumeStrength: { value: HOLOGRAM_DEFAULTS.volumeStrength, min: 0, max: 1, step: 0.01, label: "Volume Strength" },
        sphereSize: {
          value: HOLOGRAM_DEFAULTS.sphereSize,
          min: 0.003,
          max: 0.08,
          step: 0.001,
          label: "Sphere Size",
        },
      },
      { collapsed: false },
    ),
    Position: folder(
      {
        modelX: { value: HOLOGRAM_DEFAULTS.modelX, min: -5, max: 5, step: 0.05, label: "X" },
        modelY: { value: HOLOGRAM_DEFAULTS.modelY, min: -5, max: 5, step: 0.05, label: "Y" },
        modelZ: { value: HOLOGRAM_DEFAULTS.modelZ, min: -5, max: 5, step: 0.05, label: "Z" },
      },
      { collapsed: false },
    ),
    Interaction: folder(
      {
        mouseRadius: {
          value: HOLOGRAM_DEFAULTS.mouseRadius,
          min: 0.1,
          max: 5,
          step: 0.05,
          label: "Radius",
        },
        mouseStrength: {
          value: HOLOGRAM_DEFAULTS.mouseStrength,
          min: 0,
          max: 10,
          step: 0.05,
          label: "Strength",
        },
        pushStrength: {
          value: HOLOGRAM_DEFAULTS.pushStrength,
          min: 0,
          max: 30,
          step: 0.5,
          label: "Push Force",
        },
        springStiffness: {
          value: HOLOGRAM_DEFAULTS.springStiffness,
          min: 0.5,
          max: 60,
          step: 0.5,
          label: "Return Speed",
        },
        springDamping: {
          value: HOLOGRAM_DEFAULTS.springDamping,
          min: 0.1,
          max: 40,
          step: 0.1,
          label: "Return Smoothness",
        },
        mouseScatter: {
          value: HOLOGRAM_DEFAULTS.mouseScatter,
          min: 0,
          max: 3,
          step: 0.05,
          label: "Scatter",
        },
        mouseGlowColor: { value: HOLOGRAM_DEFAULTS.mouseGlowColor, label: "Glow Color" },
        mouseGlowPassive: {
          value: HOLOGRAM_DEFAULTS.mouseGlowPassive,
          min: 0,
          max: 3,
          step: 0.05,
          label: "Glow Passive",
        },
        mouseGlowActive: {
          value: HOLOGRAM_DEFAULTS.mouseGlowActive,
          min: 0,
          max: 6,
          step: 0.05,
          label: "Glow Active",
        },
        mouseGlowDecay: {
          value: HOLOGRAM_DEFAULTS.mouseGlowDecay,
          min: 0.1,
          max: 10,
          step: 0.1,
          label: "Glow Decay",
        },
        mouseGlowPow: {
          value: HOLOGRAM_DEFAULTS.mouseGlowPow,
          min: 0.5,
          max: 6,
          step: 0.1,
          label: "Glow Sharpness",
        },
        mouseLerp: {
          value: HOLOGRAM_DEFAULTS.mouseLerp,
          min: 0.5,
          max: 30,
          step: 0.5,
          label: "Follow Speed",
        },
      },
      { collapsed: false },
    ),
    PostFX: folder(
      {
        bloomStrength: {
          value: HOLOGRAM_DEFAULTS.bloomStrength,
          min: 0,
          max: 3,
          step: 0.05,
          label: "Bloom Strength",
        },
        bloomRadius: {
          value: HOLOGRAM_DEFAULTS.bloomRadius,
          min: 0,
          max: 1,
          step: 0.01,
          label: "Bloom Radius",
        },
        bloomThreshold: {
          value: HOLOGRAM_DEFAULTS.bloomThreshold,
          min: 0,
          max: 1,
          step: 0.01,
          label: "Bloom Threshold",
        },
        chromaticStr: {
          value: HOLOGRAM_DEFAULTS.chromaticStr,
          min: 0,
          max: 3,
          step: 0.05,
          label: "Chromatic Aberration",
        },
      },
      { collapsed: false },
    ),
    "Light 1": folder(
      {
        light1X: { value: HOLOGRAM_DEFAULTS.light1X, min: -10, max: 10, step: 0.1, label: "X" },
        light1Y: { value: HOLOGRAM_DEFAULTS.light1Y, min: -10, max: 10, step: 0.1, label: "Y" },
        light1Z: { value: HOLOGRAM_DEFAULTS.light1Z, min: -10, max: 10, step: 0.1, label: "Z" },
        light1Color: { value: HOLOGRAM_DEFAULTS.light1Color, label: "Color" },
        light1Intensity: { value: HOLOGRAM_DEFAULTS.light1Intensity, min: 0, max: 5, step: 0.05, label: "Intensity" },
      },
      { collapsed: false },
    ),
    "Light 2": folder(
      {
        light2X: { value: HOLOGRAM_DEFAULTS.light2X, min: -10, max: 10, step: 0.1, label: "X" },
        light2Y: { value: HOLOGRAM_DEFAULTS.light2Y, min: -10, max: 10, step: 0.1, label: "Y" },
        light2Z: { value: HOLOGRAM_DEFAULTS.light2Z, min: -10, max: 10, step: 0.1, label: "Z" },
        light2Color: { value: HOLOGRAM_DEFAULTS.light2Color, label: "Color" },
        light2Intensity: { value: HOLOGRAM_DEFAULTS.light2Intensity, min: 0, max: 5, step: 0.05, label: "Intensity" },
      },
      { collapsed: false },
    ),
    Animation: folder(
      {
        floatAmp: {
          value: HOLOGRAM_DEFAULTS.floatAmp,
          min: 0,
          max: 0.15,
          step: 0.001,
          label: "Float Amp",
        },
        autoRotateSpeed: {
          value: HOLOGRAM_DEFAULTS.autoRotateSpeed,
          min: 0,
          max: 5,
          step: 0.05,
          label: "Rotate Speed",
        },
      },
      { collapsed: false },
    ),
    Wave: folder(
      {
        noiseAmp: {
          value: HOLOGRAM_DEFAULTS.noiseAmp,
          min: 0,
          max: 1,
          step: 0.005,
          label: "Wave Amp",
        },
        noiseScale: {
          value: HOLOGRAM_DEFAULTS.noiseScale,
          min: 0.05,
          max: 3,
          step: 0.05,
          label: "Wave Scale",
        },
        noiseSpeed: {
          value: HOLOGRAM_DEFAULTS.noiseSpeed,
          min: 0,
          max: 2,
          step: 0.01,
          label: "Wave Speed",
        },
        noiseGain: {
          value: HOLOGRAM_DEFAULTS.noiseGain,
          min: 0.1,
          max: 0.9,
          step: 0.01,
          label: "Turbulence",
        },
        maskScale: {
          value: HOLOGRAM_DEFAULTS.maskScale,
          min: 0.05,
          max: 2,
          step: 0.05,
          label: "Instability Scale",
        },
        maskSpeed: {
          value: HOLOGRAM_DEFAULTS.maskSpeed,
          min: 0,
          max: 0.5,
          step: 0.005,
          label: "Instability Speed",
        },
        maskContrast: {
          value: HOLOGRAM_DEFAULTS.maskContrast,
          min: 0.1,
          max: 8,
          step: 0.1,
          label: "Instability Edge",
        },
      },
      { collapsed: false },
    ),
    Transition: folder(
      {
        transitionDeformDur: {
          value: HOLOGRAM_DEFAULTS.transitionDeformDur,
          min: 0.1,
          max: 3,
          step: 0.05,
          label: "Deform Duration",
        },
        transitionMorphDur: {
          value: HOLOGRAM_DEFAULTS.transitionMorphDur,
          min: 0.1,
          max: 4,
          step: 0.05,
          label: "Morph Duration",
        },
        transitionReformDur: {
          value: HOLOGRAM_DEFAULTS.transitionReformDur,
          min: 0.1,
          max: 3,
          step: 0.05,
          label: "Reform Duration",
        },
        transitionMaskContrast: {
          value: HOLOGRAM_DEFAULTS.transitionMaskContrast,
          min: 0.0,
          max: 2,
          step: 0.05,
          label: "Deform Amount",
        },
        transitionGlowScale: {
          value: HOLOGRAM_DEFAULTS.transitionGlowScale,
          min: 0,
          max: 4,
          step: 0.05,
          label: "Glow Scale",
        },
      },
      { collapsed: true },
    ),
    Entrance: folder(
      {
        entranceMorphDur: {
          value: HOLOGRAM_DEFAULTS.entranceMorphDur,
          min: 0.1,
          max: 3,
          step: 0.05,
          label: "Morph Duration",
        },
        entranceReformDur: {
          value: HOLOGRAM_DEFAULTS.entranceReformDur,
          min: 0.05,
          max: 2,
          step: 0.05,
          label: "Reform Duration",
        },
        replay: button(() => onReplay()),
      },
      { collapsed: true },
    ),
    Cylinder: folder(
      {
        cylVisible: { value: HOLOGRAM_DEFAULTS.cylVisible, label: "Visible" },
        cylColor: { value: HOLOGRAM_DEFAULTS.cylColor, label: "Color" },
        cylRadius: {
          value: HOLOGRAM_DEFAULTS.cylRadius,
          min: 0.5,
          max: 5,
          step: 0.05,
          label: "Radius",
        },
        cylHeight: {
          value: HOLOGRAM_DEFAULTS.cylHeight,
          min: 0.5,
          max: 10,
          step: 0.1,
          label: "Height",
        },
        cylNoiseScale: {
          value: HOLOGRAM_DEFAULTS.cylNoiseScale,
          min: 0.1,
          max: 12,
          step: 0.1,
          label: "Noise Scale",
        },
        cylLineWidth: {
          value: HOLOGRAM_DEFAULTS.cylLineWidth,
          min: 0.005,
          max: 0.5,
          step: 0.005,
          label: "Line Width",
        },
        cylFresnelPow: {
          value: HOLOGRAM_DEFAULTS.cylFresnelPow,
          min: 0.5,
          max: 8,
          step: 0.1,
          label: "Fresnel Power",
        },
        cylBaseOpacity: {
          value: HOLOGRAM_DEFAULTS.cylBaseOpacity,
          min: 0,
          max: 1,
          step: 0.01,
          label: "Base Opacity",
        },
        cylLineOpacity: {
          value: HOLOGRAM_DEFAULTS.cylLineOpacity,
          min: 0,
          max: 1,
          step: 0.01,
          label: "Line Opacity",
        },
        cylNoiseSpeed: {
          value: HOLOGRAM_DEFAULTS.cylNoiseSpeed,
          min: 0,
          max: 3,
          step: 0.05,
          label: "Noise Speed",
        },
        cylPulseSpeed: {
          value: HOLOGRAM_DEFAULTS.cylPulseSpeed,
          min: 0,
          max: 5,
          step: 0.05,
          label: "Pulse Speed",
        },
        cylPulseAmp: {
          value: HOLOGRAM_DEFAULTS.cylPulseAmp,
          min: 0,
          max: 1,
          step: 0.01,
          label: "Pulse Amount",
        },
        cylPulseEasing: {
          value: HOLOGRAM_DEFAULTS.cylPulseEasing,
          min: 1,
          max: 8,
          step: 0.1,
          label: "Pulse Easing",
        },
        cylWaveFreq: {
          value: HOLOGRAM_DEFAULTS.cylWaveFreq,
          min: 0.1,
          max: 10,
          step: 0.1,
          label: "Wave Freq",
        },
        cylTexRepeat: {
          value: HOLOGRAM_DEFAULTS.cylTexRepeat,
          min: 0.5,
          max: 20,
          step: 0.5,
          label: "Tex Repeat",
        },
        cylY: {
          value: HOLOGRAM_DEFAULTS.cylY,
          min: -5,
          max: 5,
          step: 0.05,
          label: "Position Y",
        },
      },
      { collapsed: true },
    ),
    "Dot Grid": folder(
      {
        gridVisible: { value: HOLOGRAM_DEFAULTS.gridVisible, label: "Visible" },
        gridColor: { value: HOLOGRAM_DEFAULTS.gridColor, label: "Color" },
        gridBaseOpacity: { value: HOLOGRAM_DEFAULTS.gridBaseOpacity, min: 0, max: 1, step: 0.01, label: "Base Opacity" },
        gridWaveAmp: {
          value: HOLOGRAM_DEFAULTS.gridWaveAmp,
          min: 0,
          max: 4,
          step: 0.05,
          label: "Wave Amp",
        },
        gridNoiseScale: {
          value: HOLOGRAM_DEFAULTS.gridNoiseScale,
          min: 0.01,
          max: 1,
          step: 0.01,
          label: "Wave Scale",
        },
        gridWaveSpeed: {
          value: HOLOGRAM_DEFAULTS.gridWaveSpeed,
          min: 0,
          max: 1,
          step: 0.01,
          label: "Wave Speed",
        },
        gridDensity: {
          value: HOLOGRAM_DEFAULTS.gridDensity,
          min: 0.2,
          max: 4,
          step: 0.05,
          label: "Density",
        },
        gridDotSize: {
          value: HOLOGRAM_DEFAULTS.gridDotSize,
          min: 0.01,
          max: 0.45,
          step: 0.01,
          label: "Dot Size",
        },
      },
      { collapsed: true },
    ),
    Ring: folder(
      {
        ringVisible: { value: HOLOGRAM_DEFAULTS.ringVisible, label: "Visible" },
        ringColor: { value: HOLOGRAM_DEFAULTS.ringColor, label: "Color" },
        ringThickness: { value: HOLOGRAM_DEFAULTS.ringThickness, min: 0.001, max: 0.2, step: 0.001, label: "Thickness" },
        ringBrightness: { value: HOLOGRAM_DEFAULTS.ringBrightness, min: 0, max: 10, step: 0.1, label: "Brightness" },
        ringOpacity: { value: HOLOGRAM_DEFAULTS.ringOpacity, min: 0, max: 1, step: 0.01, label: "Opacity" },
        ringRadius: {
          value: HOLOGRAM_DEFAULTS.ringRadius,
          min: 0.1,
          max: 6,
          step: 0.05,
          label: "Radius",
        },
        ringGap: {
          value: HOLOGRAM_DEFAULTS.ringGap,
          min: 0,
          max: 80,
          step: 1,
          label: "Gap (deg)",
        },
      },
      { collapsed: true },
    ),
    Background: folder(
      {
        bgColorCenter: { value: HOLOGRAM_DEFAULTS.bgColorCenter, label: "Center" },
        bgColorMid: { value: HOLOGRAM_DEFAULTS.bgColorMid, label: "Mid" },
        bgColorEdge: { value: HOLOGRAM_DEFAULTS.bgColorEdge, label: "Edge" },
      },
      { collapsed: true },
    ),
    Camera: folder(
      {
        camIntensity: {
          value: HOLOGRAM_DEFAULTS.camIntensity,
          min: 0,
          max: 40,
          step: 0.5,
          label: "Intensity",
        },
        camStiffness: {
          value: HOLOGRAM_DEFAULTS.camStiffness,
          min: 0.1,
          max: 20,
          step: 0.1,
          label: "Stiffness",
        },
        camDamping: {
          value: HOLOGRAM_DEFAULTS.camDamping,
          min: 0.1,
          max: 20,
          step: 0.1,
          label: "Damping",
        },
      },
      { collapsed: true },
    ),
  });
}
